#!/bin/bash

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

export PATH=/opt/homebrew/bin/:$PATH
eval "$(brew shellenv)"

if [ -f ~/.presentation_mode ]; then
	PRESENTATION_MODE=true
else
	PRESENTATION_MODE=false
fi

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

if [ -f ~/.bash_box_specific ]; then
    . ~/.bash_box_specific
fi

if $PRESENTATION_MODE; then
	# Docker mode
	#PS1="\n🐳  \W lucy $ "

	# Gay Mode
	#PS1="\n🏳️‍🌈  \W lucy $ "
	# PS1="\n🌈  \W lucy $ "
	#PS1="\n🌈  \W strawb $ "

	# Boring mode
	export PS1="\n $ "


	#imgcat ~/git_src/dev_utils/img/strawberry.png

	# UGUU ANIME MODE
	#PS1="\n(づ｡◕‿‿◕｡)づ 🌈  \W lucy $ "
else
	if [ -z "${LMHD_GIT_PROMPT_SKIP}" ]; then
		if [ -f "$(brew --prefix)/opt/bash-git-prompt/share/gitprompt.sh" ]; then
			#GIT_PROMPT_ONLY_IN_REPO=1
			GIT_PROMPT_THEME=Solarized
			GIT_PROMPT_START="_LAST_COMMAND_INDICATOR_ ${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\] \[\033[01;34m\]\w\[\033[00m\]"
			GIT_PROMPT_END=""
			GIT_PROMPT_FETCH_REMOTE_STATUS=1
			source "$(brew --prefix)/opt/bash-git-prompt/share/gitprompt.sh"
		fi
	fi
fi
