
"try
	" Pathogen
	"execute pathogen#infect()

	" NERDTree
	"autocmd StdinReadPre * let s:std_in=1
	"autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif
	"map <C-n> :NERDTreeToggle<CR>
"catch
"endtry

" We have colours
set t_Co=256

" Enable syntax highlighting
syntax on

" Use case insensitive search, except when using capital letters
set ignorecase
set smartcase

" Display line numbers on the left
set number

" Show tab-bar always
set showtabline=2

" Tab navigation
nnoremap <F9>  gT
nnoremap <F10> gt
set tabpagemax=100

" Tab colors
hi TabLineFill ctermfg=Blue  ctermbg=White
hi TabLineSel  ctermfg=White ctermbg=Red
hi TabLine     ctermfg=White ctermbg=Blue

" Tabs are 4 spaces
set tabstop=4
set shiftwidth=4
set softtabstop=4

" display hidden chars
set list listchars=tab:.\ ,trail:$

" highlight search results
set hlsearch

" allow deletion of indent, eol and anything which wasn't added in this vim session
set backspace=2

"test highlighting with a long line
"ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss

"highlight cols past 80
"if exists('+colorcolumn')
"	execute "set colorcolumn=" . join(range(81,335), ',')
"	highlight ColorColumn ctermbg=233
"else
"	highlight OverLength ctermbg=233
"	match OverLength /\%81v.*/
"endif


" associate *.pom with xml filetype
au BufRead,BufNewFile *.pom set filetype=xml


" compiled tcl
au BufRead,BufNewFile *.tbc set filetype=tcl



" Don't save a backup of crontabs
" http://calebthompson.io/crontab-and-vim-sitting-in-a-tree/
autocmd filetype crontab setlocal nobackup nowritebackup




set showmode  showcmd  cmdheight=1
set laststatus=2           " always show statusline

highlight StatusLine NONE ctermbg=233 ctermfg=White cterm=NONE
if has("statusline")
	set statusline =          " clear
	set statusline+=%r        " read only flag '[RO]'
	"set statusline+=%h        " help flag '[Help]'
	set statusline+=%=        " left/right separation point
	set statusline+=\ %c      " column number
	set statusline+=%V        " virtual column '-{n}'
	set statusline+=:%l/%L    " line/lines
	set statusline+=\ %p%%    " percent of file
endif
