" Enable syntax highlighting
syntax on

" Use case insensitive search, except when using capital letters
set ignorecase
set smartcase

" Enable use of the mouse for all modes
set mouse=a

" Display line numbers on the left
set number

" Show tab-bar always
set showtabline=2

" Tab navigation
nnoremap <F9>  gT
nnoremap <F10> gt

" Tab colors
hi TabLineFill ctermfg=Blue  ctermbg=White
hi TabLineSel  ctermfg=White ctermbg=Red
hi TabLine     ctermfg=White ctermbg=Blue

" Tabs are 4 spaces
set tabstop=4
set shiftwidth=4
set softtabstop=4

" display hidden chars
set list listchars=tab:.\ ,trail:$


"test highlighting with a long line
"ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss

"highlight cols past 80
if exists('+colorcolumn')
	execute "set colorcolumn=" . join(range(81,335), ',')
	highlight ColorColumn ctermbg=0
else
	highlight OverLength ctermbg=0
	match OverLength /\%81v.*/
endif


